apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app }}-service
  labels:
   app: {{ .Values.app }}
spec:
  type: ClusterIp
  ports:
    - port: {{ .Values.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.app }}
